borrar() {
AULA=/scripts/aula/bak
SCRIPTS_AULA_BAK=/scripts/aula/
SCRIPTS_BAK=/scripts/BAK
SCRIPTS_OVPN=/scripts/openvpn
SCRIPTS_VMS=/scripts/vms
SCRIPTS=/scripts
echo "
$AULA/alias.sh
$AULA/aulasrv1.vpn
$AULA/claves.sh
$AULA/config.ubu15
$AULA/copiaTrabajosClase.sh
$AULA/copiaTrabajosClase2.sh
$AULA/correoConexion.txt
$AULA/gmail.sh
$AULA/inicio.sh
$AULA/instalarTunelSsh.sh
$AULA/instiKeys.sh
$AULA/ovpn.sh
$AULA/ovpsrv.sh
$AULA/rutas.sh
$AULA/rX11vnc.sh
$AULA/sshCopyId.sh
$AULA/sshTun.sh
$AULA/start.sh
$AULA/_start.sh
$AULA/torRoute.sh
$AULA/tun.sh
$AULA/tunelSsh5.sh
$AULA/tunelSsh6.sh
$AULA/ubu.vpn
$SCRIPTS_AULA_BAK/_openvpn.sh
$SCRIPTS_AULA_BAK/tunelSsh1.5.sh
$SCRIPTS_AULA_BAK/tunelSsh2.sh
$SCRIPTS_AULA_BAK/tunelSsh2.sh~
$SCRIPTS_AULA_BAK/tunelSsh2.sh.old
$SCRIPTS_AULA_BAK/tunelSsh3.sh~
$SCRIPTS_AULA_BAK/tunelSsh4.sh
$SCRIPTS_AULA_BAK/tunelSsh4.sh~
$SCRIPTS_AULA_BAK/_tunelSsh.sh
$SCRIPTS_AULA_BAK/tunelSsh.sh
$SCRIPTS_AULA_BAK/tunelSsh.sh~
$SCRIPTS_AULA_BAK/_x11vnc.sh

$SCRIPTS_BAK/popGetSubjects.sh
$SCRIPTS_BAK/smtpSend2.sh
$SCRIPTS_BAK/smtpSend3.sh
$SCRIPTS_BAK/smtpSend4.sh
$SCRIPTS_BAK/smtpSend5.sh
$SCRIPTS_BAK/smtpSend6.sh
$SCRIPTS_OVPN/key
$SCRIPTS_OVPN/openvpn.sh
$SCRIPTS_OVPN/openvpnPuntoApunto.sh
$SCRIPTS_OVPN/openvpn_ubu.noip.me.zip
$SCRIPTS_VMS/2008.sh
$SCRIPTS_VMS/cha.txt
$SCRIPTS_VMS/leopard.sh
$SCRIPTS_VMS/mac.sh
$SCRIPTS_VMS/pararMaquinas.sh
$SCRIPTS_VMS/proxySocks.sh
$SCRIPTS_VMS/start.sh
$SCRIPTS_VMS/ubu.sh
$SCRIPTS_VMS/vmw.sh
$SCRIPTS/actualizaMulti-dvd.sh
$SCRIPTS/actualizaPen.sh
$SCRIPTS/actualizaSysrcd.sh
$SCRIPTS/alarma.sh
$SCRIPTS/alive.sh
$SCRIPTS/ap.sh
$SCRIPTS/apActual.sh
$SCRIPTS/apBuscaRed.sh
$SCRIPTS/baja.sh
$SCRIPTS/bbc.sh
$SCRIPTS/bookPass.sh
$SCRIPTS/buscaProxFtp.sh
$SCRIPTS/buscaRed.sh
$SCRIPTS/cambiaCasaInsti.sh
$SCRIPTS/cambiaCasaInstiFreeBSD.sh
$SCRIPTS/captura.sh
$SCRIPTS/cif.sh
$SCRIPTS/clase.sh
$SCRIPTS/conectVPN.sh
$SCRIPTS/confHwIfaces.sh
$SCRIPTS/dale.sh
$SCRIPTS/desencriptar.sh
$SCRIPTS/desencrypta.sh
$SCRIPTS/dnsexit.sh
$SCRIPTS/dnsexit.sh.old
$SCRIPTS/duckdns.sh
$SCRIPTS/dynDns.sh
$SCRIPTS/encriptar.sh
$SCRIPTS/encrypta.sh
$SCRIPTS/epoptes.sh
$SCRIPTS/evalua.sh
$SCRIPTS/fileserveUpload.sh
$SCRIPTS/fin.sh
$SCRIPTS/firefox.sh
$SCRIPTS/firewall.sh
$SCRIPTS/firewall.sh.old
$SCRIPTS/fireWget.sh
$SCRIPTS/franc.sh
$SCRIPTS/FRANC_FreeBSD_8
$SCRIPTS/FRANC_FreeBSD_8_1
$SCRIPTS/FRANC_GENERIC
$SCRIPTS/FRANC_GENERIC_8
$SCRIPTS/FRANC_GENERIC_8.2
$SCRIPTS/FRANC_GENERIC_8.2.old
$SCRIPTS/FRANC_GENERIC_8.old
$SCRIPTS/free.sh
$SCRIPTS/freeB.sh
$SCRIPTS/ftpHostinger.sh
$SCRIPTS/GENERIC
$SCRIPTS/getMyPass.sh
$SCRIPTS/getRealMac.sh
$SCRIPTS/git.sh
$SCRIPTS/githubGet.sh
$SCRIPTS/gmail.sh
$SCRIPTS/gmailSmtpOpensslSendSession.txt
$SCRIPTS/
$SCRIPTS/
$SCRIPTS/
$SCRIPTS/
$SCRIPTS/
$SCRIPTS/
$SCRIPTS/
$SCRIPTS/
$SCRIPTS/
$SCRIPTS/
$SCRIPTS/
$SCRIPTS/
$SCRIPTS/
$SCRIPTS/
$SCRIPTS/
$SCRIPTS/
$SCRIPTS/

"
}

[ "$(ps aux | grep -i dropbox)" ] && echo dropbox se está ejecutando. Asegúrate de que no se ejecute y vuelve a intentarlo && exit 2

borrar | while READ f; do
   rm $f;
done    
