DROP DATABASE IF EXISTS BD_BIBLIOTECA;
CREATE DATABASE BD_BIBLIOTECA  DEFAULT CHARACTER SET utf8 COLLATE utf8_spanish_ci;
GRANT ALL PRIVILEGES ON BD_BIBLIOTECA.* TO BD_BIBLIOTECA@localhost IDENTIFIED BY 'pepe';
USE BD_BIBLIOTECA;

CREATE TABLE TIPOS (
   cod TINYINT(3) UNSIGNED AUTO_INCREMENT,
   denominacion VARCHAR(20) NOT NULL,
   duracion_prestamo TINYINT UNSIGNED NOT NULL,
   PRIMARY KEY(cod)
) ENGINE=INNODB;

CREATE TABLE SOCIO (
   cod INT UNSIGNED AUTO_INCREMENT,
   nombre VARCHAR(30) NOT NULL,
   apellido1 VARCHAR(20) NOT NULL,
   apellido2 VARCHAR(20),
   dir VARCHAR(50) NOT NULL,
   cod_TIPOS TINYINT(3) UNSIGNED NOT NULL,
   PRIMARY KEY(cod),
   FOREIGN KEY(cod_TIPOS) REFERENCES TIPOS(cod) ON UPDATE CASCADE
) ENGINE=INNODB;   

CREATE TABLE EDITORIAL (
   cod INT UNSIGNED AUTO_INCREMENT,
   nombre VARCHAR(40),
   PRIMARY KEY(cod)
) ENGINE=INNODB;

CREATE TABLE LIBRO (
   cod INT UNSIGNED AUTO_INCREMENT,
   titulo VARCHAR(40) NOT NULL,
   cod_EDITORIAL INT UNSIGNED NOT NULL,
   anio_edicion SMALLINT(4) NOT NULL,
   PRIMARY KEY(cod),
   FOREIGN KEY(cod_EDITORIAL) REFERENCES EDITORIAL(cod) ON UPDATE CASCADE
) ENGINE=INNODB;

CREATE TABLE EJEMPLAR(
   cod_LIBRO INT UNSIGNED,
   num TINYINT UNSIGNED,
   PRIMARY KEY(cod_LIBRO,num),
   FOREIGN KEY(cod_LIBRO) REFERENCES LIBRO(cod) ON UPDATE CASCADE
) ENGINE=INNODB;
   
CREATE TABLE AUTOR (
   cod INT UNSIGNED AUTO_INCREMENT,
   nombre VARCHAR(30) NOT NULL,
   apellido1 VARCHAR(20) NOT NULL,
   apellido2 VARCHAR(20),
   PRIMARY KEY(cod)
) ENGINE=INNODB;
      
CREATE TABLE TEMA (
   cod INT UNSIGNED AUTO_INCREMENT,
   descripcion VARCHAR(30),
   PRIMARY KEY(cod)
) ENGINE=INNODB;
      
CREATE TABLE peticion_prestamo (
   cod_SOCIO INT UNSIGNED,
   cod_EJEMPLAR INT UNSIGNED,
   num_EJEMPLAR TINYINT UNSIGNED,
   fecha DATE,
   fecha_devol DATE,
   PRIMARY KEY(cod_SOCIO,cod_EJEMPLAR,num_EJEMPLAR,fecha),
   FOREIGN KEY(cod_SOCIO) REFERENCES SOCIO(cod) ON UPDATE CASCADE,
   FOREIGN KEY(cod_EJEMPLAR,num_EJEMPLAR) REFERENCES EJEMPLAR(cod_LIBRO,num) ON UPDATE CASCADE
) ENGINE=INNODB;
      
CREATE TABLE escribe (
   cod_LIBRO INT UNSIGNED,
   cod_AUTOR INT UNSIGNED,
   PRIMARY KEY(cod_LIBRO,cod_AUTOR),
   FOREIGN KEY(cod_LIBRO) REFERENCES LIBRO(cod) ON UPDATE CASCADE,
   FOREIGN KEY(cod_AUTOR) REFERENCES AUTOR(cod) ON UPDATE CASCADE
) ENGINE=INNODB;
   
       
CREATE TABLE trata (
   cod_LIBRO INT UNSIGNED,
   cod_TEMA INT UNSIGNED,
   PRIMARY KEY(cod_LIBRO,cod_TEMA),
   FOREIGN KEY(cod_LIBRO) REFERENCES LIBRO(cod) ON UPDATE CASCADE,
   FOREIGN KEY(cod_TEMA) REFERENCES TEMA(cod) ON UPDATE CASCADE
) ENGINE=INNODB;
          

