DROP DATABASE IF EXISTS BD_NOMINASS;
CREATE DATABASE BD_NOMINASS  DEFAULT CHARACTER SET utf8 COLLATE utf8_spanish_ci;
GRANT ALL PRIVILEGES ON BD_NOMINASS.* TO BD_NOMINASS@localhost IDENTIFIED BY 'pepe';

use BD_NOMINASS;

CREATE TABLE EMPLEADO (
   matric INT UNSIGNED AUTO_INCREMENT,
   nif CHAR(9) NOT NULL UNIQUE,
   nombre VARCHAR(20) NOT NULL,
   apellido1 VARCHAR(20) NOT NULL,
   apellido2 VARCHAR(20) NOT NULL,
   n_hijos TINYINT UNSIGNED NOT NULL,
   ret TINYINT UNSIGNED NOT NULL,
   banco SMALLINT(4) ZEROFILL UNSIGNED NOT NULL,
   sucursal SMALLINT(4) ZEROFILL UNSIGNED NOT NULL,
   dig_control TINYINT(2) UNSIGNED NOT NULL,
   cuenta BIGINT(10) NOT NULL,
   PRIMARY KEY(matric)
) ENGINE=INNODB;

CREATE TABLE DEPARTAMENTO (
   id INT UNSIGNED AUTO_INCREMENT,
   nombre VARCHAR(30),
   PRIMARY KEY(id)
) ENGINE=INNODB;

CREATE TABLE SEDE (
   id_DEPARTAMENTO INT UNSIGNED,
   nombre VARCHAR(30),
   PRIMARY KEY(id_DEPARTAMENTO,nombre)
) ENGINE=INNODB;

CREATE TABLE JUSTIFICANTE (
   matric_EMPLEADO INT UNSIGNED,
   n_orden TINYINT UNSIGNED,
   mes TINYINT(2) ZEROFILL UNSIGNED,
   ejercicio SMALLINT(4) UNSIGNED, 
   ingreso DECIMAL(10,2) NOT NULL,
   descuento DECIMAL(10,2) NOT NULL,
   PRIMARY KEY(matric_EMPLEADO,n_orden,mes,ejercicio),
   FOREIGN KEY(matric_EMPLEADO) REFERENCES EMPLEADO(matric) ON UPDATE CASCADE
) ENGINE=INNODB;

CREATE TABLE CONCEPRET (
   cod INT UNSIGNED AUTO_INCREMENT,
   descripcion VARCHAR(30),
   PRIMARY KEY(cod)
) ENGINE=INNODB;   

CREATE TABLE LINEA (
   matric_JUSTIFICANTE INT UNSIGNED,
   n_orden_JUSTIFICANTE TINYINT UNSIGNED,
   mes_JUSTIFICANTE TINYINT(2) UNSIGNED ZEROFILL,
   ejercicio_JUSTIFICANTE SMALLINT(4) UNSIGNED,
   n_linea TINYINT UNSIGNED,
   cantidad DECIMAL(10,2) NOT NULL,
   base DECIMAL(10,2),
   porcentaje TINYINT UNSIGNED,
   cod_CONCEPTRET INT UNSIGNED,
   PRIMARY KEY(matric_JUSTIFICANTE,n_orden_JUSTIFICANTE,mes_JUSTIFICANTE,ejercicio_JUSTIFICANTE,n_linea),
   FOREIGN KEY(matric_JUSTIFICANTE,n_orden_JUSTIFICANTE,mes_JUSTIFICANTE,ejercicio_JUSTIFICANTE) REFERENCES JUSTIFICANTE(matric_EMPLEADO,n_orden,mes,ejercicio) ON UPDATE CASCADE
) ENGINE=INNODB;

CREATE TABLE ECOSTE (
   cod INT UNSIGNED AUTO_INCREMENT,
   descripcion VARCHAR(30) NOT NULL,
   saldo DECIMAL(10,2) NOT NULL,
   cod_ECOSTE INT UNSIGNED,
   PRIMARY KEY(cod),
   FOREIGN KEY(cod_ECOSTE) REFERENCES ECOSTE(cod) ON UPDATE CASCADE
) ENGINE=INNODB;

CREATE TABLE TRANSF (
   cod INT UNSIGNED AUTO_INCREMENT,
   banco SMALLINT(4) ZEROFILL UNSIGNED NOT NULL,
   sucursal SMALLINT(4) ZEROFILL UNSIGNED NOT NULL,
   dig_control TINYINT(2) UNSIGNED NOT NULL,
   cuenta BIGINT(10) NOT NULL,
   cantidad DECIMAL(10,2) NOT NULL,
   PRIMARY KEY(cod)
) ENGINE=INNODB;

CREATE TABLE APUNTE (
   cod INT UNSIGNED AUTO_INCREMENT,
   cantidad DECIMAL(10,2) NOT NULL,
   PRIMARY KEY(cod)
) ENGINE=INNODB;

CREATE TABLE trabaja (
   matric_EMPLEADO INT UNSIGNED,
   id_DEPARTAMENTO INT UNSIGNED,
   funcion VARCHAR(20),
   PRIMARY KEY(matric_EMPLEADO,id_DEPARTAMENTO),
   FOREIGN KEY(matric_EMPLEADO) REFERENCES EMPLEADO(matric) ON UPDATE CASCADE,
   FOREIGN KEY(id_DEPARTAMENTO) REFERENCES DEPARTAMENTO(id) ON UPDATE CASCADE
) ENGINE=INNODB;

CREATE TABLE se_imputa (
   matric_LINEA INT UNSIGNED,
   n_orden_LINEA TINYINT UNSIGNED,
   mes_LINEA TINYINT(2) ZEROFILL UNSIGNED,
   ejercicio_LINEA SMALLINT(4) UNSIGNED,
   n_linea_LINEA TINYINT UNSIGNED,
   cod_ECOSTE INT UNSIGNED,
   PRIMARY KEY(matric_LINEA,n_orden_LINEA,mes_LINEA,ejercicio_LINEA,n_linea_LINEA,cod_ECOSTE),
   FOREIGN KEY(matric_LINEA,n_orden_LINEA,mes_LINEA,ejercicio_LINEA,n_linea_LINEA) REFERENCES LINEA(matric_JUSTIFICANTE,n_orden_JUSTIFICANTE,mes_JUSTIFICANTE,ejercicio_JUSTIFICANTE,n_linea) ON UPDATE CASCADE,
   FOREIGN KEY(cod_ECOSTE) REFERENCES ECOSTE(cod) ON UPDATE CASCADE
) ENGINE=INNODB;

CREATE TABLE se_liquida (
   cod_ECOSTE INT UNSIGNED,
   cod_APUNTE INT UNSIGNED,
   cod_TRANSF INT UNSIGNED,
   fecha DATE NOT NULL,
   PRIMARY KEY(cod_ECOSTE,cod_APUNTE,cod_TRANSF),
   FOREIGN KEY(cod_ECOSTE) REFERENCES ECOSTE(cod) ON UPDATE CASCADE,
   FOREIGN KEY(cod_APUNTE) REFERENCES APUNTE(cod) ON UPDATE CASCADE,
   FOREIGN KEY(cod_TRANSF) REFERENCES TRANSF(cod) ON UPDATE CASCADE
) ENGINE=INNODB;
   
   
   
      
