#!/bin/bash 
macsAulas() {
echo "dhcp-host=00:19:66:e9:3b:f6,pc101,10.2.1.101,infinite
dhcp-host=00:19:66:e9:3b:7a,pc102,10.2.1.102,infinite
dhcp-host=00:19:66:e9:42:17,pc103,10.2.1.103,infinite
dhcp-host=00:19:66:e9:3b:4f,pc104,10.2.1.104,infinite
dhcp-host=00:19:66:e9:3d:88,pc105,10.2.1.105,infinite
dhcp-host=00:19:66:e9:3b:2d,pc106,10.2.1.106,infinite
dhcp-host=00:19:66:e9:3d:30,pc107,10.2.1.107,infinite
dhcp-host=00:19:66:e9:3b:89,pc108,10.2.1.108,infinite
dhcp-host=00:19:66:f0:d1:0c,pc109,10.2.1.109,infinite
dhcp-host=00:19:66:e9:3e:7e,pc110,10.2.1.110,infinite
dhcp-host=00:19:66:e9:3c:78,pc111,10.2.1.111,infinite
dhcp-host=00:19:66:e9:3b:77,pc112,10.2.1.112,infinite
dhcp-host=00:19:66:e9:3b:be,pc113,10.2.1.113,infinite
dhcp-host=00:19:66:e9:41:f9,pc114,10.2.1.114,infinite
dhcp-host=00:19:66:e9:3b:7e,pc115,10.2.1.115,infinite
dhcp-host=00:19:66:e9:3f:07,pc116,10.2.1.116,infinite
dhcp-host=00:19:66:e9:3b:46,pc117,10.2.1.117,infinite
dhcp-host=00:19:66:e9:3e:ed,pc118,10.2.1.118,infinite
dhcp-host=00:19:66:e9:3c:59,pc119,10.2.1.119,infinite
dhcp-host=00:19:66:e9:3b:ac,pc120,10.2.1.120,infinite
dhcp-host=00:19:66:e9:42:07,pc121,10.2.1.121,infinite
dhcp-host=00:19:66:e9:42:12,pc122,10.2.1.122,infinite
dhcp-host=00:19:66:e9:3c:75,pc123,10.2.1.123,infinite
dhcp-host=00:19:66:e9:3b:b4,pc124,10.2.1.124,infinite
dhcp-host=00:19:66:e9:3b:32,pc125,10.2.1.125,infinite
dhcp-host=00:19:66:e9:3c:89,pc126,10.2.1.126,infinite
dhcp-host=00:19:66:e9:3b:e6,pc127,10.2.1.127,infinite
dhcp-host=00:19:66:e9:3b:7b,pc128,10.2.1.128,infinite
dhcp-host=00:19:66:e9:3b:9d,pc129,10.2.1.129,infinite
dhcp-host=00:1a:a0:bc:88:f1,pc201,10.2.1.201,infinite
dhcp-host=00:1d:60:d8:69:b5,pc202,10.2.1.202,infinite
dhcp-host=00:1e:8c:07:da:3b,pc203,10.2.1.203,infinite
dhcp-host=00:1d:60:d8:69:c5,pc204,10.2.1.204,infinite
dhcp-host=00:1e:8c:07:da:3a,pc205,10.2.1.205,infinite
dhcp-host=00:1d:60:b4:54:06,pc206,10.2.1.206,infinite
dhcp-host=00:19:66:e9:3b:93,pc207,10.2.1.207,infinite
dhcp-host=00:1d:60:d8:69:b7,pc208,10.2.1.208,infinite
dhcp-host=00:1d:60:d8:69:ae,pc209,10.2.1.209,infinite
dhcp-host=00:1d:60:d8:69:bf,pc210,10.2.1.210,infinite
dhcp-host=00:1e:8c:26:40:e1,pc211,10.2.1.211,infinite
dhcp-host=70:71:bc:ae:dd:35,pc212,10.2.1.212,infinite
dhcp-host=00:1e:8c:26:43:b0,pc213,10.2.1.213,infinite
dhcp-host=00:1a:92:d6:d6:fd,pc214,10.2.1.214,infinite
dhcp-host=00:1d:60:b4:53:d5,pc215,10.2.1.215,infinite
dhcp-host=00:1e:8c:26:40:d9,pc216,10.2.1.216,infinite
dhcp-host=20:cf:30:55:b3:95,pc217,10.2.1.217,infinite
dhcp-host=70:71:bc:ae:e4:35,pc218,10.2.1.218,infinite
dhcp-host=70:71:bc:ae:de:1d,pc219,10.2.1.219,infinite
dhcp-host=70:71:bc:ae:e1:72,pc220,10.2.1.220,infinite"
}

ponerHostname() {
   #ETH=$(ifconfig -a | grep -E 'eth[0-9]{1,2}' | head -1 | awk '{print $1;}')
   #MAC=$(cat /sys/class/net/$ETH/address)
   MAC=$(ip address show | grep -i ether | awk '{print $2;}')
   PCNUM=$(macsAulas | grep $MAC | awk -F',' '{print $3;}' | awk -F'.' '{print $4;}' )
   echo "pc$PCNUM"
}
ejecutarEnCliente() {
   MONTAJE="$1"
   ESTA=$(cat $MONTAJE/etc/sudoers | grep "lliurex ALL = NOPASSWD: ALL")
   if [ "$ESTA" = "" ]; then
      echo lliurex ALL = NOPASSWD: ALL >> $MONTAJE/etc/sudoers
   fi
   mkdir -p $MONTAJE/home/lliurex/.ssh
   echo "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDCBlkziUqHifjpH3WxWNHWPIOXpzddS1CCd7X3y7beWzCRxJ49IEdwoY8cTYytA14D989oG3EVNM18t+hqEKo/YEf/spW6Frzi+c1TASOFXAwBZ6etHK2eWsn2lZkX85Oht/ZyKsUQEfolcLJfPA0jOuqBnXWn4kYb55cPtUnZRO2VeoRADEpgxty0ohdh5D3Q6gZRd7GSO7ZkJUWooWOjxf4kUSJSbd6mANwa2HfX5HnbgNSK8NUrx++e4uGzJZIyNXuZSz8bOh2xiuBnG7IrB+kTITH8uys+gvLG22k06k9wxtIsR+HEzHgNc2/LUmJlDzDv25+kRfF/MYd+npfF franav@aulasrv1 franav@srv2aula" >> $MONTAJE/home/lliurex/.ssh/authorized_keys
   echo "|1|WCoAbukj+ma0mmzkfd0RtEO6+iw=|WlOG9kcsWZ0ghlRqvSE8UUixxlU= ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBA/dQpXvMvYJ+qdDrbf9s/gxWi5cTpBSEuhq+Xyk0ll8vPjOqay985D1SGTcVvXX8Uhp42lxthXHdTSUr2K96Oo=" >> $MONTAJE/home/lliurex/.ssh/known_hosts
   chown -R lliurex:lliurex $MONTAJE/home/lliurex/.ssh
   echo "sudo x11vnc -noshm -24to32 -connect_or_exit server:\$1 -auth /var/run/lightdm/root/:0 -display :0" > $MONTAJE/usr/local/bin/pantalla
   chmod +x $MONTAJE/usr/local/bin/pantalla
}
lliurex15_04() {
   IMAGEN_FSA=$(ls /livemnt/boot/fsImages/lliurex15.04/*.fsa)
   fsarchiver restfs -v $IMAGEN_FSA id=0,dest=$DEV$PART_LLIUREX
   MONTAJE=/mnt/lliurex
   mkdir -p $MONTAJE

   mount $DEV$PART_LLIUREX $MONTAJE 
   if [ ! -f $MONTAJE/bin/zsh ]; then
      cp /bin/zsh $MONTAJE/bin/ 
   fi
   mount --bind /dev $MONTAJE/dev 
   mount --bind /dev/pts $MONTAJE/dev/pts 
   mount --bind /proc $MONTAJE/proc 
   mount --bind /sys $MONTAJE/sys 

   chroot $MONTAJE grub-install --recheck $DEV 
   ########################
   ## poner timeout del grub a cero
   sed -i "s/$(grep GRUB_TIMEOUT $MONTAJE/etc/default/grub)/GRUB_TIMEOUT=10/g" $MONTAJE/etc/default/grub

   chroot $MONTAJE update-grub
   chroot $MONTAJE update-grub2 

   hdparm -f $DEV
   sync
   umount $MONTAJE/dev/pts 
   umount $MONTAJE/dev 
   umount $MONTAJE/proc 
   umount $MONTAJE/sys 
   ###################################################
   #Crear el fstab
   echo "# /etc/fstab: static file system information.
   #
   # Use 'blkid' to print the universally unique identifier for a
   # device; this may be used with UUID= as a more robust way to name devices
   # that works even if disks are added and removed. See fstab(5).
   #
   # <file system> <mount point>   <type>  <options>       <dump>  <pass>
   proc            /proc           proc    nodev,noexec,nosuid 0       0
   # / was on /dev/sda1 during installation" > $MONTAJE/etc/fstab
   UUID=$(blkid | grep $DEV$PART_LLIUREX | cut -f 2 -d " ")
   echo "$UUID     /               ext4    errors=remount-ro 0       1" >> $MONTAJE/etc/fstab
   #UUID=37ab8c50-6e05-4bce-9dc0-aea538354e36 /               ext4    errors=remount-ro 0       1
   echo "# swap was on /dev/sda5 during installation" >> /etc/fstab
   UUID=$(blkid | grep $DEV$PART_SWAP | cut -f 2 -d " ")
   echo "$UUID     none            swap    sw              0       0" >> $MONTAJE/etc/fstab
   #UUID=da63144f-ed41-4c76-a733-9b090c1dcced none            swap    sw              0       0
   ###################################################
   
   rm  $MONTAJE/etc/udev/rules.d/70-persistent-net.rules
   mkdir -p $MONTAJE/home/lliurex/.ssh
   ejecutarEnCliente $MONTAJE
   ponerHostname > $MONTAJE/etc/hostname
   umount $MONTAJE
   sync
}


DEV_ARRANQUE=$(mount | grep '/livemnt/boot' | awk '{print $1;}')
DEV=$(ls /dev/sd* | egrep -v '[0-9]' | head -1)
if [ "$DEV" = "" ];
then
   DEV=$(ls /dev/hd* | egrep -v '[0-9]' | head -1)
fi
if [ "$DEV" = "" -o "$(echo $DEV_ARRANQUE | grep $DEV)" != "" ];
then
   echo No se encontró dispositivo donde instalar el S.O.
   echo "Apagar(s/n)?"
   read RESP
   if [ "$RESP" = "s" -o "$RESP" = "S" ]; then /sbin/poweroff; fi
   exit 1
fi
DEVSIZE=$(parted -s $DEV unit B print | grep -E "$DEV: [0-9]+" | cut -f 3 -d " " | tr -d B) 
MEMSIZE=$(free | grep Mem | awk '{print $2;}')
parted $DEV --script -- mklabel msdos 
parted $DEV --script -- mkpart primary ext4 1 96%
parted $DEV --script -- mkpart primary linux-swap 96% -1
PART_LLIUREX=1
PART_SWAP=2

partprobe $DEV
mkswap $DEV$PART_SWAP
#echo fsarchiver -v -A -a -z 9 -s 640 -j 8 -c - savefs /c/COPIAS/ubuntu-sda5/ubuntu-sda5.fsa $DEV"1"
#fsarchiver restfs -v $(ls /livemnt/boot/fsImages/*.fsa) id=0,dest=$DEV"1"
   
lliurex15_04
poweroff

